apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: https://aiif-logging.es.us-east-2.aws.elastic-cloud.com:443
    database: "*"
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: 8gwuBTOzZjmVMVqSMLqqtEcP
    jsonData:
      esVersion: 8.7.0
      timeField: "@timestamp"
      interval: Daily
      logMessageField: message
      logLevelField: severity
      maxConcurrentShardRequests: 5
      tlsSkipVerify: false
    editable: true
